import turtle
import time

window = turtle.Screen()
window.bgcolor("#000000")

leonardo = turtle.Turtle()
leonardo.color('red')
leonardo.pensize(7)
leonardo.speed(3)
leonardo.shape('turtle')


leonardo.forward(-90)
leonardo.left(90)
leonardo.forward(-90)
leonardo.left(90)
leonardo.forward(-90)
leonardo.left(90)
leonardo.forward(-90)
leonardo.left(-90)

raphael = turtle.Turtle()
raphael.color('yellow')
raphael.pensize(8)
raphael.shape('turtle')
raphael.speed(2)

raphael.penup()
raphael.forward(100)
raphael.pendown()
raphael.left(90)
raphael.forward(100)
raphael.left(90)
raphael.forward(100)
raphael.left(90)
raphael.forward(100)
raphael.left(90)
raphael.forward(100)

donatello = turtle.Turtle()
donatello.color('blue')
donatello.pensize(9)
donatello.speed(2)
donatello.shape('turtle')

donatello.penup()
donatello.backward(-100)
donatello.pendown()
donatello.backward(-90)
donatello.left(-90)
donatello.forward(90)
donatello.left(-90)
donatello.forward(90)
donatello.left(-90)
donatello.forward(90)
donatello.left(-90)
donatello.forward(90)

michaelA = turtle.Turtle()
michaelA.color('purple')
michaelA.pensize(10)
michaelA.shape('turtle')
michaelA.speed(1)

michaelA.penup()
michaelA.forward(-100)
michaelA.pendown()
michaelA.right(90)
michaelA.forward(-100)
michaelA.left(90)
michaelA.forward(-100)
michaelA.left(90)
michaelA.forward(-100)
michaelA.left(90)
michaelA.forward(-100)

time.sleep(5)